ALTER TABLE `orders`
    ADD COLUMN `trail_url` VARCHAR(500) DEFAULT NULL COMMENT '快递100地图轨迹URL',
    ADD COLUMN `route_from` VARCHAR(200) DEFAULT NULL COMMENT '始发地',
    ADD COLUMN `route_cur` VARCHAR(200) DEFAULT NULL COMMENT '当前位置',
    ADD COLUMN `route_to` VARCHAR(200) DEFAULT NULL COMMENT '目的地';
